import { useEffect, useState } from "react";
import type { GalleryItem, Post, SiteContent } from "@tpb/contracts";
import { api } from "../../lib/api";
import { Band, CollectionState, formatDate } from "./ui";

export function DetailSections({ content }: { content: SiteContent }) {
  const { profil, akademik, penelitian, pengabdian, kemahasiswaan } = content;
  return <>
    <Band id="sejarah" tone="white" kicker={profil.sejarah.kicker} title={profil.sejarah.title} intro={profil.sejarah.intro}><div className="grid gap-4 md:grid-cols-2">{profil.sejarah.timeline.map((item) => <div key={`${item.year}-${item.text}`} className="reveal rounded-2xl border border-midnight/10 bg-cream p-5"><span className="font-mono text-sm text-leaf-600">{item.year}</span><p className="mt-2 text-sm leading-relaxed text-midnight/70">{item.text}</p></div>)}</div></Band>
    <Band id="visi-misi" kicker={profil.visiMisi.kicker} title={profil.visiMisi.title}><div className="grid gap-5 lg:grid-cols-2"><div className="reveal rounded-3xl bg-midnight p-7 text-white"><span className="font-mono text-xs uppercase tracking-wider text-gold">Visi</span><p className="mt-4 font-display text-2xl font-bold">{profil.visiMisi.visi}</p></div><div className="reveal rounded-3xl bg-leaf-600 p-7 text-white"><span className="font-mono text-xs uppercase tracking-wider text-gold">Misi</span><ul className="mt-4 space-y-3 text-sm leading-relaxed">{profil.visiMisi.misi.map((item) => <li key={item}>✦ {item}</li>)}</ul></div></div></Band>
    <Band id="struktur" tone="white" kicker={profil.struktur.kicker} title={profil.struktur.title}><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{profil.struktur.people.map((person) => <div key={`${person.role}-${person.name}`} className="reveal rounded-2xl border border-midnight/10 bg-cream p-5"><p className="text-xs uppercase tracking-wider text-leaf-600">{person.role}</p><p className="mt-2 font-display text-xl font-bold text-midnight">{person.name}</p></div>)}</div></Band>
    <Band id="sambutan" kicker={profil.sambutan.kicker} title={profil.sambutan.title}><div className="grid gap-8 lg:grid-cols-[260px_1fr] lg:items-center"><img src={profil.sambutan.image} alt={profil.sambutan.name} className="reveal h-64 w-full rounded-3xl object-cover" /><div className="reveal"><p className="font-display text-2xl italic leading-relaxed text-midnight">“{profil.sambutan.quote}”</p><p className="mt-5 font-bold text-midnight">{profil.sambutan.name}</p><p className="text-sm text-midnight/55">{profil.sambutan.role}</p></div></div></Band>
    <Band id="kurikulum" tone="white" kicker={akademik.kurikulum.kicker} title={akademik.kurikulum.title} intro={akademik.kurikulum.intro}><MetricList items={akademik.kurikulum.sks} /><TagList items={akademik.kurikulum.clusters} /></Band>
    <Band id="kalender" kicker={akademik.kalender.kicker} title={akademik.kalender.title}><Timeline items={akademik.kalender.items.map((x) => ({ year: x.d, text: x.e }))} /></Band>
    <Band id="dosen" tone="white" kicker={akademik.dosen.kicker} title={akademik.dosen.title} intro={akademik.dosen.intro}><People items={akademik.dosen.people.map((x) => ({ name: x.name, role: x.field }))} /></Band>
    <Band id="laboratorium" kicker={akademik.laboratorium.kicker} title={akademik.laboratorium.title}><Cards items={akademik.laboratorium.labs.map((x) => ({ title: x.name, body: x.desc }))} /></Band>
    <Band id="publikasi" tone="white" kicker={penelitian.publikasi.kicker} title={penelitian.publikasi.title}><Cards items={penelitian.publikasi.pubs.map((x) => ({ title: x.title, body: `${x.venue} · ${x.year}` }))} /></Band>
    <Band id="jurnal" kicker={penelitian.jurnal.kicker} title={penelitian.jurnal.title} intro={penelitian.jurnal.intro}><Cards items={penelitian.jurnal.cards.map((x) => ({ title: x.title, body: x.body, note: x.note }))} /></Band>
    <Band id="kolaborasi" tone="white" kicker={penelitian.kolaborasi.kicker} title={penelitian.kolaborasi.title} intro={penelitian.kolaborasi.intro}><TagList items={penelitian.kolaborasi.partners} /></Band>
    <Band id="program-desa" kicker={pengabdian.programDesa.kicker} title={pengabdian.programDesa.title}><Cards items={pengabdian.programDesa.desa.map((x) => ({ title: x.name, body: x.body }))} /></Band>
    <Band id="kemitraan" tone="white" kicker={pengabdian.kemitraan.kicker} title={pengabdian.kemitraan.title}><TagList items={pengabdian.kemitraan.mitra} /></Band>
    <Band id="kegiatan" kicker={pengabdian.kegiatan.kicker} title={pengabdian.kegiatan.title}><Timeline items={pengabdian.kegiatan.items.map((x) => ({ year: x.t, text: x.d }))} /></Band>
    <Band id="himpunan" tone="white" kicker={kemahasiswaan.himpunan.kicker} title={kemahasiswaan.himpunan.title} intro={kemahasiswaan.himpunan.intro}><TagList items={kemahasiswaan.himpunan.divisi} /></Band>
    <Band id="beasiswa" kicker={kemahasiswaan.beasiswa.kicker} title={kemahasiswaan.beasiswa.title}><Cards items={kemahasiswaan.beasiswa.items.map((x) => ({ title: x.name, body: x.body }))} /></Band>
    <Band id="prestasi" tone="white" kicker={kemahasiswaan.prestasi.kicker} title={kemahasiswaan.prestasi.title}><TagList items={kemahasiswaan.prestasi.items} /></Band>
    <Band id="alumni" kicker={kemahasiswaan.alumni.kicker} title={kemahasiswaan.alumni.title}><div className="grid gap-5 lg:grid-cols-2"><blockquote className="reveal rounded-3xl bg-midnight p-7 font-display text-2xl italic text-white">“{kemahasiswaan.alumni.quote}”<footer className="mt-5 font-sans text-sm not-italic text-white/60">{kemahasiswaan.alumni.name} · {kemahasiswaan.alumni.role}</footer></blockquote><MetricList items={kemahasiswaan.alumni.stats} /></div></Band>
  </>;
}

function MetricList({ items }: { items: { v: string; l: string }[] }) { return <div className="grid grid-cols-2 gap-4">{items.map((item) => <div key={`${item.v}-${item.l}`} className="reveal rounded-2xl border border-midnight/10 bg-white p-5"><p className="font-display text-3xl font-extrabold text-leaf-600">{item.v}</p><p className="mt-1 text-xs text-midnight/55">{item.l}</p></div>)}</div>; }
function TagList({ items }: { items: string[] }) { return <div className="flex flex-wrap gap-3">{items.map((item) => <span key={item} className="reveal rounded-full border border-midnight/15 bg-white px-5 py-3 text-sm text-midnight/70">{item}</span>)}</div>; }
function Timeline({ items }: { items: { year: string; text: string }[] }) { return <div className="grid gap-4 md:grid-cols-2">{items.map((item) => <div key={`${item.year}-${item.text}`} className="reveal rounded-2xl border border-midnight/10 bg-white p-5"><span className="font-mono text-sm text-leaf-600">{item.year}</span><p className="mt-2 text-sm leading-relaxed text-midnight/70">{item.text}</p></div>)}</div>; }
function People({ items }: { items: { name: string; role: string }[] }) { return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{items.map((item) => <div key={`${item.name}-${item.role}`} className="reveal rounded-2xl border border-midnight/10 bg-cream p-5"><p className="font-display text-xl font-bold text-midnight">{item.name}</p><p className="mt-2 text-sm text-midnight/55">{item.role}</p></div>)}</div>; }
function Cards({ items }: { items: { title: string; body: string; note?: string }[] }) { return <div className="grid gap-4 md:grid-cols-2">{items.map((item) => <article key={`${item.title}-${item.body}`} className="reveal rounded-2xl border border-midnight/10 bg-white p-6"><h3 className="font-display text-xl font-bold text-midnight">{item.title}</h3><p className="mt-3 text-sm leading-relaxed text-midnight/65">{item.body}</p>{item.note && <p className="mt-3 font-mono text-xs text-leaf-600">{item.note}</p>}</article>)}</div>; }

export function News({ news }: { news: SiteContent["news"] }) {
  const [posts, setPosts] = useState<Post[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [active, setActive] = useState<Post | null>(null); const [tab, setTab] = useState("all");
  useEffect(() => { let alive = true; api.listPublic().then((items) => alive && setPosts(items)).catch((e: Error) => alive && setError(e.message)).finally(() => alive && setLoading(false)); return () => { alive = false; }; }, []);
  const categories = ["all", ...Array.from(new Set(posts.map((post) => post.category)))]; const shown = tab === "all" ? posts : posts.filter((post) => post.category === tab);
  return <section id="berita" className="scroll-mt-24 bg-cream py-24"><div className="mx-auto max-w-[1360px] px-5 lg:px-10"><div className="reveal flex flex-wrap items-end justify-between gap-6"><div><span className="font-mono text-[11px] uppercase tracking-[0.3em] text-leaf-600">{news.kicker}</span><h2 className="mt-4 font-display text-4xl font-extrabold leading-tight text-midnight lg:text-5xl">{news.title}</h2></div><div className="flex flex-wrap gap-2">{categories.map((category) => <button key={category} onClick={() => setTab(category)} className={`rounded-full px-5 py-2.5 text-[13px] font-bold capitalize ${tab === category ? "bg-midnight text-white" : "border border-midnight/12 text-midnight/60"}`}>{category === "all" ? "Semua" : category}</button>)}</div></div><CollectionState loading={loading} error={error} empty={!shown.length}><div className="mt-12 grid gap-7 md:grid-cols-2 lg:grid-cols-3">{shown.map((post) => <article key={post.id} onClick={() => setActive(post)} className="reveal group flex cursor-pointer flex-col overflow-hidden rounded-3xl border border-midnight/8 bg-white transition hover:-translate-y-1.5"><div className="relative h-52 overflow-hidden bg-midnight/10">{post.image && <img src={post.image} alt={post.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" />}<span className="absolute left-4 top-4 rounded-full bg-gold px-3 py-1 font-mono text-[10px] font-bold uppercase tracking-wider text-midnight">{post.category}</span></div><div className="flex flex-1 flex-col p-6"><div className="font-mono text-[11px] uppercase tracking-wider text-midnight/45">{formatDate(post.date)} · {post.readTime}</div><h3 className="mt-3 flex-1 font-display text-xl font-bold leading-snug text-midnight">{post.title}</h3><span className="mt-5 text-[13px] font-bold text-midnight/70">Selengkapnya →</span></div></article>)}</div></CollectionState></div>{active && <div onClick={() => setActive(null)} className="fixed inset-0 z-[90] grid place-items-center overflow-y-auto bg-midnight/70 p-4 backdrop-blur-sm"><article onClick={(event) => event.stopPropagation()} className="w-full max-w-2xl overflow-hidden rounded-3xl bg-white shadow-2xl">{active.image && <img src={active.image} alt={active.title} className="h-64 w-full object-cover" />}<div className="p-8"><div className="font-mono text-[11px] uppercase text-midnight/45">{active.category} · {formatDate(active.date)}</div><h3 className="mt-4 font-display text-3xl font-extrabold text-midnight">{active.title}</h3><p className="mt-5 whitespace-pre-line text-[16px] leading-relaxed text-midnight/70">{active.content || active.excerpt}</p><button onClick={() => setActive(null)} className="mt-8 rounded-full bg-midnight px-6 py-3 text-[13px] font-bold text-white">Tutup</button></div></article></div>}</section>;
}

export function CTA({ cta, onDaftar }: { cta: SiteContent["cta"]; onDaftar: () => void }) { return <section className="bg-cream pb-24"><div className="mx-auto max-w-[1360px] px-5 lg:px-10"><div className="reveal relative overflow-hidden rounded-[2.5rem] bg-gradient-to-br from-leaf-600 via-leaf to-leaf-600 px-8 py-16 text-center lg:px-20"><h2 className="relative mx-auto max-w-2xl font-display text-4xl font-extrabold leading-tight text-white lg:text-5xl">{cta.title}</h2><p className="relative mx-auto mt-5 max-w-xl text-[16px] text-white/85">{cta.body}</p><div className="relative mt-9 flex flex-wrap justify-center gap-4"><button onClick={onDaftar} className="rounded-full bg-white px-8 py-4 text-sm font-extrabold text-leaf-600">{cta.primary}</button><a href="#akademik" className="rounded-full border border-white/50 px-8 py-4 text-sm font-bold text-white">{cta.secondary}</a></div></div></div></section>; }

export function Footer({ footer, onDaftar }: { footer: SiteContent["footer"]; onDaftar: () => void }) {
  const [email, setEmail] = useState(""); const [status, setStatus] = useState<"idle" | "sending" | "sent" | "error">("idle"); const [gallery, setGallery] = useState<GalleryItem[]>([]); const [galleryError, setGalleryError] = useState(false);
  useEffect(() => { api.listGallery().then((items) => setGallery(items.slice(0, 6))).catch(() => setGalleryError(true)); }, []);
  const subscribe = async (event: React.FormEvent) => { event.preventDefault(); if (!email.trim()) return; setStatus("sending"); try { await api.subscribe(email); setEmail(""); setStatus("sent"); } catch { setStatus("error"); } };
  return <footer className="relative bg-midnight text-white"><div className="mx-auto grid max-w-[1360px] gap-14 px-5 py-20 lg:grid-cols-[1.4fr_1fr_1fr_1.2fr] lg:px-10"><div><h3 className="font-display text-3xl font-extrabold leading-tight">{footer.newsletterTitle}</h3><form onSubmit={subscribe} className="mt-7 flex max-w-md items-center rounded-full border border-white/15 bg-white/5 p-1.5"><input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} className="flex-1 bg-transparent px-5 py-2.5 text-sm text-white placeholder:text-white/40 focus:outline-none" /><button disabled={status === "sending"} className="rounded-full bg-gold px-6 py-2.5 text-xs font-extrabold text-midnight">{status === "sending" ? "…" : status === "sent" ? "Terkirim ✓" : status === "error" ? "Gagal ✕" : "Submit"}</button></form><p className="mt-9 text-xs font-bold uppercase tracking-[0.2em] text-white/55">{footer.tagline}</p></div><div><h4 className="font-display text-xl font-bold">Informasi</h4><ul className="mt-6 space-y-4 text-sm text-white/70"><li>{footer.contact.phone}</li><li>{footer.contact.email}</li><li>{footer.contact.address}</li></ul></div><div><h4 className="font-display text-xl font-bold">Tautan Cepat</h4><ul className="mt-6 space-y-3.5 text-sm text-white/70">{footer.quickLinks.map((link) => <li key={link.href}><a href={link.href} className="hover:text-white">{link.label}</a></li>)}<li><button onClick={onDaftar} className="hover:text-white">{footer.copyright}</button></li></ul></div><div><h4 className="font-display text-xl font-bold">Galeri</h4>{galleryError ? <p className="mt-6 text-sm text-white/50">Galeri tidak dapat dimuat.</p> : <div className="mt-6 grid grid-cols-3 gap-2.5">{gallery.map((item) => <a key={item.id} href={item.link || item.image} target={item.link ? "_blank" : undefined} rel="noreferrer" className="aspect-square overflow-hidden rounded-xl bg-white/10"><img src={item.image} alt={item.caption || ""} className="h-full w-full object-cover" /></a>)}</div>}</div></div><div className="border-t border-white/10"><div className="mx-auto flex max-w-[1360px] justify-between gap-3 px-5 py-6 text-xs text-white/50 lg:px-10"><p>{footer.copyright}</p><p>{footer.tagline}</p></div></div></footer>;
}

export function BackToTop() { const [show, setShow] = useState(false); useEffect(() => { const onScroll = () => setShow(window.scrollY > 600); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []); return <button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} aria-label="Kembali ke atas" className={`fixed bottom-7 right-7 z-40 grid h-12 w-12 place-items-center rounded-full bg-gold text-midnight transition-all ${show ? "opacity-100" : "pointer-events-none opacity-0"}`}>↑</button>; }
