import { useEffect, useState } from "react";
import type { NavItem, SiteContent } from "@tpb/contracts";
import { Crest } from "./ui";

export function Header({ brand, navigation, onAdmin }: { brand: SiteContent["brand"]; navigation: NavItem[]; onAdmin: () => void }) {
  const [scrolled, setScrolled] = useState(false);
  const [open, setOpen] = useState<string | null>(null);
  const [mobile, setMobile] = useState(false);
  const [logoFailed, setLogoFailed] = useState(false);
  useEffect(() => setLogoFailed(false), [brand.logoUrl]);
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 24); onScroll(); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []);
  return <header className="fixed inset-x-0 top-0 z-50"><div className={`transition-all duration-500 ${scrolled ? "bg-cream/85 backdrop-blur-xl shadow-[0_10px_40px_-24px_rgba(14,16,68,0.6)]" : "bg-cream/0"}`}><div className="mx-auto flex max-w-[1360px] items-center gap-6 px-5 py-3.5 lg:px-10"><a href="#top" className="flex shrink-0 items-center gap-3">{brand.logoUrl && !logoFailed ? <img src={brand.logoUrl} alt={`${brand.name} logo`} className="h-11 w-11 object-contain drop-shadow-sm" onError={() => setLogoFailed(true)} /> : <Crest className="h-11 w-11 drop-shadow-sm" />}<span className="leading-none"><span className="block font-mono text-[9px] font-medium uppercase tracking-[0.32em] text-leaf-600">{brand.kicker}</span><span className="block font-display text-[15px] font-extrabold leading-tight text-midnight">{brand.name}</span><span className="block text-[10px] font-semibold uppercase tracking-[0.18em] text-midnight/55">{brand.org}</span></span></a><nav className="ml-auto hidden items-center gap-0.5 xl:flex" onMouseLeave={() => setOpen(null)}>{navigation.map((item) => <div key={item.href} className="relative" onMouseEnter={() => setOpen(item.label)}><a href={item.href} className="rounded-full px-4 py-2.5 text-[12px] font-bold text-midnight/70 transition hover:bg-midnight/5 hover:text-midnight">{item.label}</a>{item.children?.length && open === item.label ? <div className="absolute left-1/2 top-full mt-2 w-56 -translate-x-1/2 rounded-2xl border border-midnight/10 bg-white p-2 shadow-xl">{item.children.map((child) => <a key={child.href} href={child.href} className="block rounded-xl px-3 py-2 text-sm text-midnight/70 hover:bg-cream hover:text-midnight">{child.label}</a>)}</div> : null}</div>)}<button onClick={onAdmin} className="ml-3 rounded-full bg-midnight px-5 py-2.5 text-[12px] font-bold text-white transition hover:bg-midnight-700">Admin</button></nav><button onClick={() => setMobile(!mobile)} className="ml-auto rounded-full border border-midnight/15 px-4 py-2 text-xs font-bold xl:hidden" aria-expanded={mobile}>Menu</button></div>{mobile && <nav className="border-t border-midnight/10 bg-cream px-5 py-4 xl:hidden">{navigation.map((item) => <div key={item.href}><a href={item.href} onClick={() => setMobile(false)} className="block py-2 text-sm font-bold text-midnight">{item.label}</a>{item.children?.map((child) => <a key={child.href} href={child.href} onClick={() => setMobile(false)} className="block py-1 pl-4 text-xs text-midnight/60">{child.label}</a>)}</div>)}<button onClick={onAdmin} className="mt-3 rounded-full bg-midnight px-5 py-2.5 text-xs font-bold text-white">Admin</button></nav>}</div></header>;
}

export function Hero({ hero, onDaftar }: { hero: SiteContent["hero"]; onDaftar: () => void }) {
  return <section id="top" className="relative min-h-screen overflow-hidden bg-midnight"><div className="absolute inset-0"><img src={hero.image} alt="" className="h-full w-full object-cover opacity-45" /><div className="absolute inset-0 bg-gradient-to-r from-midnight via-midnight/80 to-midnight/20" /></div><div className="relative mx-auto flex min-h-screen max-w-[1360px] items-center px-5 pb-20 pt-32 lg:px-10"><div className="max-w-3xl text-white"><span className="reveal inline-flex rounded-full border border-gold/50 bg-gold/10 px-4 py-2 font-mono text-xs uppercase tracking-[0.22em] text-gold">{hero.badge}</span><h1 className="reveal mt-7 font-display text-5xl font-extrabold leading-[0.95] lg:text-8xl">{hero.line1}<br /><span className="text-gold">{hero.highlight}</span><br />{hero.line2}</h1><p className="reveal mt-7 max-w-xl text-base leading-relaxed text-white/75 lg:text-lg">{hero.subtitle}</p><div className="reveal mt-9 flex flex-wrap gap-3"><button onClick={onDaftar} className="rounded-full bg-gold px-7 py-3.5 text-sm font-extrabold text-midnight transition hover:-translate-y-0.5">{hero.primaryLabel}</button><a href={hero.primaryHref} className="rounded-full border border-white/30 px-7 py-3.5 text-sm font-bold text-white transition hover:bg-white/10">{hero.secondaryLabel}</a></div></div></div></section>;
}

export function Marquee({ items }: { items: string[] }) { return <div className="overflow-hidden bg-gold py-3 text-midnight"><div className="marquee-track flex min-w-max gap-8 font-mono text-xs font-bold uppercase tracking-[0.2em]">{[...items, ...items].map((item, index) => <span key={`${item}-${index}`} className="flex items-center gap-8">{item}<span>✦</span></span>)}</div></div>; }
