import type { SiteContent } from "@tpb/contracts";
import { Band } from "./ui";

export function Stats({ items }: { items: SiteContent["stats"] }) { return <section className="bg-cream py-20"><div className="mx-auto grid max-w-[1360px] grid-cols-2 gap-5 px-5 lg:grid-cols-4 lg:px-10">{items.map((item) => <div key={`${item.label}-${item.value}`} className="reveal rounded-3xl border border-midnight/10 bg-white p-6"><p className="font-display text-4xl font-extrabold text-midnight">{item.value}<span className="text-gold">{item.suffix}</span></p><p className="mt-2 text-sm text-midnight/60">{item.label}</p></div>)}</div></section>; }

export function About({ about }: { about: SiteContent["about"] }) { return <Band id="profil" kicker={about.kicker} title={about.title} intro={about.body} tone="cream"><div className="grid gap-10 lg:grid-cols-[1fr_1.1fr] lg:items-center"><div className="reveal overflow-hidden rounded-[2rem] bg-midnight"><img src={about.image} alt="" className="h-full max-h-[520px] w-full object-cover" /></div><div className="space-y-7"><div className="reveal rounded-3xl bg-midnight p-7 text-white"><p className="font-display text-5xl font-extrabold text-gold">{about.sinceYear}</p><p className="mt-2 text-sm text-white/70">{about.sinceNote}</p></div><ul className="reveal grid gap-3">{about.points.map((point) => <li key={point} className="flex items-start gap-3 rounded-2xl border border-midnight/10 bg-white p-4 text-sm text-midnight/70"><span className="mt-1 text-leaf-600">✦</span>{point}</li>)}</ul></div></div></Band>; }

export function Programs({ programs, onDaftar }: { programs: SiteContent["programs"]; onDaftar: () => void }) { return <Band id="akademik" tone="white" kicker={programs.kicker} title={programs.title}><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{programs.cards.map((card) => <article key={`${card.tag}-${card.title}`} className="reveal group overflow-hidden rounded-3xl bg-midnight text-white"><div className="h-52 overflow-hidden"><img src={card.img} alt="" className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /></div><div className="p-6"><span className="font-mono text-xs uppercase tracking-wider text-gold">{card.tag}</span><h3 className="mt-3 font-display text-2xl font-bold">{card.title}</h3><p className="mt-3 text-sm leading-relaxed text-white/65">{card.body}</p></div></article>)}</div><button onClick={onDaftar} className="mt-8 rounded-full bg-midnight px-7 py-3.5 text-sm font-bold text-white hover:bg-midnight-700">{programs.cta}</button></Band>; }

export function Research({ research }: { research: SiteContent["research"] }) { return <Band id="penelitian" kicker={research.kicker} title={research.title} intro={research.body}><div className="grid gap-5 lg:grid-cols-2">{research.areas.map((area) => <article key={area.no} className="reveal rounded-3xl bg-midnight p-7 text-white"><span className="font-mono text-gold">{area.no}</span><h3 className="mt-5 font-display text-2xl font-bold">{area.title}</h3><p className="mt-3 text-sm leading-relaxed text-white/65">{area.body}</p></article>)}</div><div className="mt-6 grid grid-cols-2 gap-4 md:grid-cols-4">{research.metrics.map((metric) => <div key={`${metric.v}-${metric.l}`} className="reveal rounded-2xl border border-midnight/10 bg-white p-5"><p className="font-display text-3xl font-extrabold text-leaf-600">{metric.v}</p><p className="mt-1 text-xs text-midnight/55">{metric.l}</p></div>)}</div></Band>; }

export function Community({ community }: { community: SiteContent["community"] }) { return <Band id="pengabdian" tone="white" kicker={community.kicker} title={community.title} intro={community.body}><div className="grid gap-8 lg:grid-cols-[1.1fr_1fr] lg:items-center"><img src={community.image} alt="" className="reveal max-h-[500px] w-full rounded-[2rem] object-cover" /><ul className="reveal space-y-3">{community.items.map((item) => <li key={item} className="rounded-2xl bg-cream p-5 text-sm leading-relaxed text-midnight/75">{item}</li>)}</ul></div></Band>; }

export function StudentLife({ studentLife, onDaftar }: { studentLife: SiteContent["studentLife"]; onDaftar: () => void }) { return <Band id="kemahasiswaan" kicker={studentLife.kicker} title={studentLife.title}><div className="grid gap-5 md:grid-cols-3">{studentLife.cards.map((card) => <article key={`${card.tag}-${card.title}`} className="reveal rounded-3xl border border-midnight/10 bg-white p-7"><span className="font-mono text-xs uppercase tracking-wider text-leaf-600">{card.tag}</span><h3 className="mt-4 font-display text-2xl font-bold text-midnight">{card.title}</h3><p className="mt-3 text-sm leading-relaxed text-midnight/65">{card.body}</p></article>)}</div><button onClick={onDaftar} className="mt-8 rounded-full bg-gold px-7 py-3.5 text-sm font-extrabold text-midnight">{studentLife.cta}</button></Band>; }
